//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePostOffice_5001.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ORDER
    {
        public int ORDERID { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<int> CUSTOMER { get; set; }
        public Nullable<byte> AMOUNT { get; set; }
    
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
        public virtual TBLUSER TBLUSER { get; set; }
    }
}
